In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("data_cleaning_sample.csv")

In [25]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [26]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [27]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [28]:
df2 = df.dropna()
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [29]:
df2.duplicated()

0    False
2    False
4    False
6     True
7     True
dtype: bool

In [30]:
df2.drop_duplicates()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019

In [31]:
df2["Name"].str.upper()

0    ALICE
2      BOB
4    DAVID
6    ALICE
7    ALICE
Name: Name, dtype: str

In [32]:
df2["City"].str.lower()

0       new york
2    los angeles
4         mumbai
6       new york
7       new york
Name: City, dtype: str

In [45]:
df["Age"] = df["Age"].fillna(0).astype(int)
df

      Name  Age         City Gender              Email   Join Date
0    Alice   25     New York      F  alice@example.com  01-05-2021
1  Charlie    0        Delhi      M    charlie@example  20-07-2021
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie    0        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
5      NaN   28        Delhi      F     eve@domain.com         NaN
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
8  Charlie    0        Delhi      M    charlie@example  20-07-2021

In [49]:
df["Join Date"] = pd.to_datetime(df["Join Date"], format="mixed", errors="coerce")
df

      Name  Age         City Gender              Email  Join Date
0    Alice   25     New York      F  alice@example.com 2021-01-05
1  Charlie    0        Delhi      M    charlie@example 2021-07-20
2      Bob   30  Los Angeles      M    bob@example.com 2020-06-15
3  Charlie    0        Delhi      M    charlie@example 2021-07-20
4    David   22       Mumbai      M  david@example.com 2019-12-11
5      NaN   28        Delhi      F     eve@domain.com        NaT
6    Alice   25     New York      F  alice@example.com 2021-01-05
7    Alice   25     New York      F  alice@example.com 2021-01-05
8  Charlie    0        Delhi      M    charlie@example 2021-07-20

In [50]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x > 25 else "Minor")

In [51]:
df

      Name  Age         City Gender              Email  Join Date Age Group
0    Alice   25     New York      F  alice@example.com 2021-01-05     Minor
1  Charlie    0        Delhi      M    charlie@example 2021-07-20     Minor
2      Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
3  Charlie    0        Delhi      M    charlie@example 2021-07-20     Minor
4    David   22       Mumbai      M  david@example.com 2019-12-11     Minor
5      NaN   28        Delhi      F     eve@domain.com        NaT     Adult
6    Alice   25     New York      F  alice@example.com 2021-01-05     Minor
7    Alice   25     New York      F  alice@example.com 2021-01-05     Minor
8  Charlie    0        Delhi      M    charlie@example 2021-07-20     Minor

In [53]:
gender_map={"F": "Female", "M": "Male"}
df["Gender"] = df["Gender"].map(gender_map)

In [54]:
df

      Name  Age         City  Gender              Email  Join Date Age Group
0    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
1  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor
2      Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
3  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor
4    David   22       Mumbai    Male  david@example.com 2019-12-11     Minor
5      NaN   28        Delhi  Female     eve@domain.com        NaT     Adult
6    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
7    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
8  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor

In [56]:
df["City"].replace({"Delhi":"New Delhi", "New York": "NYK"})

0            NYK
1      New Delhi
2    Los Angeles
3      New Delhi
4         Mumbai
5      New Delhi
6            NYK
7            NYK
8      New Delhi
Name: City, dtype: str

In [57]:
df

      Name  Age         City  Gender              Email  Join Date Age Group
0    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
1  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor
2      Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
3  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor
4    David   22       Mumbai    Male  david@example.com 2019-12-11     Minor
5      NaN   28        Delhi  Female     eve@domain.com        NaT     Adult
6    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
7    Alice   25     New York  Female  alice@example.com 2021-01-05     Minor
8  Charlie    0        Delhi    Male    charlie@example 2021-07-20     Minor